README.md, makroer/tests/Episode_of_care_test.sas, makroer/tests/aggreger_test.sas, makroer/tests/boomraader_test.sas, makroer/tests/hyppigste_test.sas, makroer/tests/reinnleggelser_test.sas, makroer/tests/unik_pasient_test.sas
SAS libref `skde_tst` renamed to `test`
=> Changed libref on test-folder

makroer/alders_oppslag.sas, makroer/andelsfig.sas, makroer/forholdstall.sas, makroer/merge.sas, makroer/oversiktstabell_helseatlas.sas, makroer/panelfig.sas, makroer/ratefig.sas, makroer/ratefig_todeltSoyle.sas, makroer/ratefig_tredeltSoyle.sas, makroer/rater_felles.sas, makroer/rater_felles_18.sas, makroer/tabell.sas
**Ready to be merged into master**
=> Included macros from gyn.obs. atlas

makroer/test_rateprogram.sas, rateprogram/sas/definerVariabler.sas, rateprogram/tests/makroer.sas, rateprogram/tests/tests.sas
=> Fix rateprogram testing framework

makroer/VarFraParvus.sas
- The default, for now, is to run with t17.
- Reorg. the macro as well (removed duplication of code)
=> Macro varfraparvus both working with t17 and t18

rateprogram/rateberegninger.sas, rateprogram/sas/ekskluderingstabeller.sas, rateprogram/sas/utvalgx.sas
=> Rateprogram: Moved ekskl.tabell out of utvalgX

formater/NPR_AvtSpes.sas, formater/NPR_Psyk.sas, formater/NPR_somatikk.sas
```
410	Allergologi	Ny kode fra 2017
420	Sykelig overvekt	Ny kode fra 2017
430	Smertetilstander	Ny kode fra 2017
```
=> Added three new fagomrade formats

rateprogram/sas/definere_format.sas
Was previously tabulated with dots. Fixes #41
=> Rateprogram: use comma in tables if Excel

rateprogram/sas/ekskluderingstabeller.sas
=> Rateprogram: Better tables of excluded contacts

makroer/Episode_of_care.sas, tests/Episode_of_care_test.sas, tests/data/eoc6.csv
=> Fix bug in EoC macro for separer_ut_poli

tilrettelegging/npr/1_kontroll_foer_tilrette/simpletab_loop.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/tabulate_variabler.sas
make the list of string variable dynamic, input from sas project.
=> string variables

makroer/forny_komnr.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_behandlingssted.sas
Laget forslag til dokumentasjon av makro kontroll_behandlingssted. Ser det forståelig ut? 
Fikset samtidig filbane i makroen forny_komnr.
=> Markdown kontrollbehandlingssted

tilrettelegging/npr/2_tilrettelegging/fix_behandlingssted.sas
Diakonhjemmet kodet enkelt kontakter med behandlingsstedkode2 = 999999999 i 2017
=> Diakonhjemmet-fiks.

formater/boomr.csv
I ratefig står HN med 7777/8888, må oppdatere csv for å fikse det.
=> legg til rad med "7777 Helse Nord" i format

formater/bo_csv_fmtfil.sas
lengde på boshhn må settes til 4. for å kunne ta med "7777" eller "8888"
=> fix lengde boshhn

rateprogram/proc_stdrate.sas
Har ordnet fast rekkefølge og farge på menn og kvinner i aldersfordelingsfigurene
=> Ratefig - ordne på aldersfordelingsfigurer

rateprogram/proc_stdrate.sas, rateprogram/ratefigur_tredelt.sas
Skrivfeil i rateprogram: asending endret til ascending to steder
Rekkefølge for søylen for Norge ordnet i proc sgplot
=> Skrivefeil rateprog + rejkkefolge tredelt

tilrettelegging/hresept/tilrettelegging.sas
Beholder de samme variablene som i tidligere tilrettelagt datasett (konsesjonsdata, `skde20.t20_legemidler_2019`).
=> Tilrettelegging av H-resept-data

formater/NPR_somatikk.sas, formater/avtalespesialister.csv, formater/avtspes_csv_fmtfil.sas, formater/behandler.csv, formater/drg.sas, makroer/forny_komnr.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_behandlingssted.sas, tilrettelegging/npr/2_tilrettelegging/Formater.sas, tilrettelegging/npr/2_tilrettelegging/avledede.sas, tilrettelegging/npr/2_tilrettelegging/bydel.sas, tilrettelegging/npr/2_tilrettelegging/def_aspes_kontakt.sas, tilrettelegging/npr/2_tilrettelegging/fix_behandlingssted.sas, tilrettelegging/npr/2_tilrettelegging/koblingsID.sas, tilrettelegging/npr/2_tilrettelegging/konvertering.sas, tilrettelegging/npr/2_tilrettelegging/lablerFormater.sas, tilrettelegging/npr/2_tilrettelegging/reduser_lengde.sas, tilrettelegging/npr/2_tilrettelegging/var_rekkefolge.sas
Tilrettelegging ferdig. Gjenstår kontroll av data.
=> tilrettelegging avtspes og somatikk RHF

rateprogram/ratefigur_5aarsvar.sas, rateprogram/ratefigur_aarsvar.sas
Endret størrelse og farge på symboler for årsvariasjon. 
Laget en kopi med litt endrede symboler tilpasset en 5-årig ratefigur.
=> Ratefig aarsvar

formater/behandler.csv, formater/drg.sas, tilrettelegging/npr/2_tilrettelegging/fix_behandlingssted.sas, tilrettelegging/npr/2_tilrettelegging/koblingsID.sas, tilrettelegging/npr/2_tilrettelegging/konvertering.sas, tilrettelegging/npr/2_tilrettelegging/lablerFormater.sas, tilrettelegging/npr/2_tilrettelegging/reduser_lengde.sas
Div endringer gjort ifbm tilrettelegging. Kan vente til etter sommerferien :)
=> div endringer kode tilrettelegging

tilrettelegging/kpr/2_tilrettelegge/kpr_avledede.sas, tilrettelegging/kpr/2_tilrettelegge/kpr_diagnoser.sas, tilrettelegging/kpr/2_tilrettelegge/kpr_icpc2.sas, tilrettelegging/kpr/2_tilrettelegge/kpr_lablerFormater.sas, tilrettelegging/kpr/2_tilrettelegge/kpr_lengde_variabler.sas, tilrettelegging/kpr/2_tilrettelegge/kpr_var_rekkefolge.sas
KPR 2022 T1 er ferdig tilrettelagt. Små endringer i koden fra sist gang.
=> tilrettelegge 2022 T1

tilrettelegging/hresept/lengde_formater.sas, tilrettelegging/hresept/tilrettelegging.sas
Det kom ny utlevering av alle STG-dataene pga feil i løpenummerserien. 
Feilen var primært i stg phv og stg som. 
Har tilrettelagt hresept på nytt, med noen små endringer.
=> endringer tilrettelegge hresept

makroer/sykehusopphold.sas
Fikset bug som gjorde at sho_id ikke var unik (tror jeg hvertfall!) 
Resultatene med ny og gammel makro er nesten identiske, fikk noen hundre opphold i differanse. 
Oppretter PR nå, men det kan vente til etter sommerferien å kontrollere.
=> Sykehusopphold

tilrettelegging/npr/2_tilrettelegging/behandler.sas, tilrettelegging/npr/2_tilrettelegging/lablerFormater.sas, tilrettelegging/npr/2_tilrettelegging/reduser_lengde.sas
små justeringer tilpasset T2-data.
=> mindre tilpasninger til T2-data

tilrettelegging/npr/1_kontroll_foer_tilrette/aktivitet_komnr_bydel.sas
Makro for å kontrollere om det er aktivitet for alle kommuner og bydeler. Kan også teste data uten bydeler.
=> closes #153

tilrettelegging/radiologi/omkoding_komnr_bydel.sas, tilrettelegging/radiologi/tilrettelegging_radiologi.sas
fornye kommunenummer til behandler
=> fornye komnr behandler

tilrettelegging/radiologi/radiologi_utvalg.sas
=> Fix ct toraks

makroer/estimere.sas, makroer/fremskrive.sas
=> nye makroer - fremskrive og estimere

tilrettelegging/radiologi/forlop_forste_andre_dager.sas
Har kun tatt med nødvendige variable. Har beholdt noen slik at det genererte datasettet kan brukes til å kjøre rater. Har også tatt med proc univariate
=> Oppdatert forløps-makroen

tilrettelegging/radiologi/tilrettelegging_radiologi.sas, tilrettelegging/radiologi/trans_dup.sas
ny makro trans_dup som kjøres i tilrettelegging_radiologi makro som førstesteg.
=> transpose dup rader

tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_behandlingssted.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_mottatte_data.sas
Endre output fra kontroll av behandlingssted
=> Ktr behandlingssted

tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_behandlingssted.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_type.sas
Legge til kommentar tilknyttet variabler som ikke alltid kommer med forventet type (numerisk eller string)
=> Kontroll variabler

makroer/forny_komnr.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/aktivitet_komnr_bydel.sas, tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_mottatte_data.sas
legge til steg i kontroll av mottatte data
=> Kontroll aktivitet komnrbydel

formater/boomr.csv, rateprogram/proc_stdrate.sas, rateprogram/proc_stdrate_komnr.sas
Makro for å kjøre rate på kommunenivå. 
I motsetning til det vanlige rateprogrammet lagrer denne output til angitt lagringssted/bildesti.
=> Rate komnr

tilrettelegging/kpr/2_tilrettelegge/kpr_kontakttype.sas
new changes to kpr tilrettelegging
=> new file kpr_kontakttype

tilrettelegging/npr/1_kontroll_foer_tilrette/kontroll_tilstand.sas
La til litt ekstra informasjon for sjekk av diagnosekoder:
=> La til litt ekstra informasjon om feil diagnosekoder under tilrettelegging

tilrettelegging/lab/KPR_utvalg.sas
Add a new code for the overall MB analysis, not part of the utvalg for the atlas.
=> ny takst for hematologi

formater/behandler.csv
Oppdatert navn på flere av organisasjonsnummer. Teres har skiftet navn til Aleris. Lagt til ett nytt orgnr.
=> oppdatert behandler.csv
